#!/bin/bash

symlink () {
  if [ -L "$2" ]; then
    true # pass
  elif [ -e "$2" ]; then
    >&2 echo "$2 exist!"
  else
    ln -s "$1" "$2"
  fi
}

DOT_DIR="$HOME/.dotfiles/dot"
for fn in `ls "$DOT_DIR"`; do
  symlink "$DOT_DIR/$fn" "$HOME/.$fn"
done

CONFIG_DIR="$HOME/.dotfiles/config"
for dn in `ls "$CONFIG_DIR"`; do
  if [ -d "$HOME/.config/$dn" ]; then
    for fn in `ls "$CONFIG_DIR/$dn"`; do
      symlink "$CONFIG_DIR/$dn/$fn" "$HOME/.config/$dn/$fn"
    done
  fi
done

git config --global core.excludesfile $HOME/.gitignore
